"""
Delphi ML Prediction Service — On-chain Flow Signal

Provides a supplementary probability signal from real on-chain trade flow.

Architecture:
1. Fetches real historical trade data from the Delphi Goldsky subgraph (GraphQL).
2. Engineers flow features: buy/sell pressure, YES-side share, momentum, trader count.
3. Combines them with a transparent, bounded heuristic anchored to the current
   market price.

Design note: an earlier version trained a GradientBoostingClassifier per request
on synthetic labels generated by the same heuristic. That model could only
re-learn the heuristic while inflating confidence (isotonic calibration on a
deterministic rule pushes outputs toward 0/1), so the consumer weighted noise
as if it were signal. The heuristic is now used directly, with honest, modest
confidence, and the TypeScript side caps this signal's weight accordingly.
"""

from fastapi import FastAPI
from pydantic import BaseModel
import numpy as np
import requests
from typing import Optional
import logging

try:
    from textblob import TextBlob
    HAS_TEXTBLOB = True
except ImportError:
    HAS_TEXTBLOB = False

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("delphi-ml")

app = FastAPI(title="Delphi Flow Signal Service")

SUBGRAPH_URL = (
    "https://api.goldsky.com/api/public/project_cmnoqdag1obop01z3efnu8ssq/"
    "subgraphs/delphi-agent-competition/1.0.0/gn"
)


class PredictionRequest(BaseModel):
    market_address: str
    current_implied_prob: float
    question: str
    headlines: Optional[list[str]] = None


class PredictionResponse(BaseModel):
    probability: float
    confidence: float
    features_used: dict
    method: str


def fetch_market_trades(market_address: str) -> tuple[list[dict], list[dict]]:
    """Fetch real buy and sell trades from the Delphi Goldsky subgraph."""

    buy_query = """
    {
        gatewayBuys(
            first: 200,
            orderBy: timestamp_,
            orderDirection: desc,
            where: { marketProxy: "%s" }
        ) {
            id
            timestamp_
            buyer
            outcomeIdx
            tokensIn
            sharesOut
        }
    }
    """ % market_address

    sell_query = """
    {
        gatewaySells(
            first: 200,
            orderBy: timestamp_,
            orderDirection: desc,
            where: { marketProxy: "%s" }
        ) {
            id
            timestamp_
            seller
            outcomeIdx
            sharesIn
            tokensOut
        }
    }
    """ % market_address

    buys, sells = [], []

    try:
        resp = requests.post(SUBGRAPH_URL, json={"query": buy_query}, timeout=15)
        resp.raise_for_status()
        buys = resp.json().get("data", {}).get("gatewayBuys", [])
    except Exception as e:
        logger.warning(f"Failed to fetch buys from subgraph: {e}")

    try:
        resp = requests.post(SUBGRAPH_URL, json={"query": sell_query}, timeout=15)
        resp.raise_for_status()
        sells = resp.json().get("data", {}).get("gatewaySells", [])
    except Exception as e:
        logger.warning(f"Failed to fetch sells from subgraph: {e}")

    return buys, sells


def engineer_features(
    buys: list[dict],
    sells: list[dict],
    current_implied_prob: float,
    headlines: list[str] | None,
) -> dict:
    """Build flow features from on-chain trade data (+ optional headline sentiment)."""

    features = {}

    buy_amounts, buy_yes_amounts = [], []
    buyers = set()
    for b in buys:
        tokens = int(b.get("tokensIn") or 0)
        buy_amounts.append(tokens)
        buyers.add(b.get("buyer"))
        if str(b.get("outcomeIdx")) == "0":
            buy_yes_amounts.append(tokens)

    sell_amounts = []
    sellers = set()
    for s in sells:
        sell_amounts.append(int(s.get("tokensOut") or 0))
        sellers.add(s.get("seller"))

    total_buy = sum(buy_amounts)
    total_sell = sum(sell_amounts)
    total_yes_buy = sum(buy_yes_amounts)

    features["buy_volume_total"] = total_buy
    features["sell_volume_total"] = total_sell
    features["yes_buy_fraction"] = (total_yes_buy / total_buy) if total_buy > 0 else 0.5
    features["trade_count"] = len(buys) + len(sells)
    features["unique_traders"] = len(buyers | sellers)

    # Momentum: newest 25% of buys vs the rest (desc order)
    if len(buy_amounts) >= 4:
        split = len(buy_amounts) // 4
        recent, older = sum(buy_amounts[:split]), sum(buy_amounts[split:])
        features["recent_momentum"] = (recent / older) if older > 0 else 1.0
    else:
        features["recent_momentum"] = 1.0

    features["current_implied_prob"] = current_implied_prob

    if headlines and HAS_TEXTBLOB:
        polarities = [TextBlob(h).sentiment.polarity for h in headlines]
        features["sentiment_score"] = float(np.mean(polarities))
    else:
        features["sentiment_score"] = 0.0

    return features


def build_prediction(features: dict) -> tuple[float, float, str]:
    """
    Transparent flow heuristic, anchored to the market price.

    The signal is a bounded ADJUSTMENT to the current implied probability, not
    an independent estimate: on-chain flow says which way informed money leans,
    but the market price already contains most information. Confidence scales
    with how much actual trading activity backs the signal, capped low —
    flow is weak evidence for how a market will literally resolve.
    """
    anchor = features["current_implied_prob"]

    # Direction signals in [-1, 1]
    yes_lean = (features["yes_buy_fraction"] - 0.5) * 2          # who is being bought
    momentum = float(np.clip(features["recent_momentum"] - 1.0, -1, 1))
    sentiment = float(np.clip(features["sentiment_score"], -1, 1))

    signal = 0.6 * yes_lean + 0.25 * momentum + 0.15 * sentiment

    # Max adjustment ±8 points, scaled by activity depth.
    activity = min(features["trade_count"] / 50.0, 1.0)
    probability = float(np.clip(anchor + 0.08 * signal * activity, 0.02, 0.98))

    # Honest confidence: thin markets → near zero; deep markets → still modest.
    traders = min(features["unique_traders"] / 20.0, 1.0)
    confidence = float(np.clip(0.1 + 0.3 * activity * traders, 0.0, 0.4))

    return probability, confidence, "flow_heuristic_v2"


@app.post("/predict", response_model=PredictionResponse)
def predict_probability(req: PredictionRequest):
    logger.info(f"Prediction request for market: {req.market_address}")

    buys, sells = fetch_market_trades(req.market_address)
    logger.info(f"Fetched {len(buys)} buys and {len(sells)} sells from subgraph.")

    if len(buys) == 0 and len(sells) == 0:
        return PredictionResponse(
            probability=req.current_implied_prob,
            confidence=0.0,
            features_used={"note": "No trade history available. Returning market price."},
            method="no_data_passthrough",
        )

    features = engineer_features(buys, sells, req.current_implied_prob, req.headlines)
    probability, confidence, method = build_prediction(features)
    logger.info(f"Prediction: {probability:.4f} (confidence: {confidence:.4f}, method: {method})")

    return PredictionResponse(
        probability=probability,
        confidence=confidence,
        features_used=features,
        method=method,
    )


@app.get("/health")
def health():
    return {"status": "ok", "service": "delphi-flow-signal"}
